services:
  - type: web
    name: gestion-des-lieux
    runtime: docker
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:lieux_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - key: APP_UPLOAD_DIR
        value: /tmp/uploads/images
      - key: AUTH_TOKEN_JWT_SECRET
        generateValue: true
      - key: APP_SHARE_BASE_URL
        value: https://gestion-des-lieux.onrender.com
